#version: "3.7"

services:

#  postgres:
#    image: postgres:17.4
#    hostname: postgres
#    container_name: postgres
#    networks:
#      - sonarnetwork
#    environment:
#      - POSTGRES_USER=sonar
#      - POSTGRES_PASSWORD=sonar
#      - POSTGRES_DB=sonar
#    volumes:
#      - postgresql:/var/lib/postgresql/data

  sonarqube:
    hostname: sonarqube
    container_name: sonarqube
    image: sonarqube:9.9.8-community
#    depends_on:
#      - postgres
    ports:
      - "8086:9000"
    networks:
      - sonarnetwork
    environment:
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.auth.allowUsersToSignUp=true
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions

#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    restart: unless-stopped
#    depends_on:
#      - postgres
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#      PGADMIN_DEFAULT_PASSWORD: ${sonar:-admin}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin_data:/var/lib/pgadmin
#    ports:
#      - "8087:80"
#    networks:
#      - sonarnetwork

networks:
  sonarnetwork:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
#  postgresql:
#  pgadmin_data:
#    driver: local
