apiVersion: apps/v1
kind: Deployment
metadata:
  name: desigan-tasksmanager-app
  labels:
    app: desigan-tasksmanager-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: desigan-tasksmanager-app
  template:
    metadata:
      labels:
        app: desigan-tasksmanager-app
    spec:
      containers:
        - name: desigan-tasksmanager-app
          image: desigan12/tasksmanager:latest
          ports:
            - containerPort: 8082