apiVersion: v1
kind: Service
metadata:
  name: tasksmanager-app-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: tasksmanager-app